services:

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: idkwhyureadthis
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: prac-project

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U idkwhyureadthis -d prac-project"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrations:
    build: migrations/
    environment:
      DBHOST: db
      DBUSER: idkwhyureadthis
      DBPASSWORD: 12345
      DBSSL: disable
      DBPORT: 5432
      DBNAME: prac-project
    depends_on:
      db:
        condition: service_healthy      


volumes:
  postgres_data: